### ISSUE TITLE
[BUG] Backup log filenames show incorrect dates

### ISSUE THREAD

**Issue by fami-t** [akamai/uls#18] opened 2022-01-13 09:07 UTC
**Describe the bug**
ULS client is configured for ETP THREAT, AUP & DNS feeds output to file, rotated at midnight, with 5 backup files.
Backup log filenames show incorrect dates (month, day, year) when compared to file timestamps. See attachments for screenshots
```
filename etp_DNS.log.2021-11-15 has OS file timestamp = Dec 14 23:59
filename etp_AUP.log.2021-11-14 has OS file timestamp = Dec 13 23:59
From file listing taken on 11-Jan-2022. Note day discrepancy is > 1
filename etp_DNS.log.2021-12-12 has OS file timestamp = Jan 10 23:59
filename etp_DNS.log.2021-12-08 has OS file timestamp = Jan  6 23:59
```
OS date/time info
```
# timedatectl
Local time: Fri 2021-12-17 14:09:34 AEDT
Universal time: Fri 2021-12-17 03:09:34 UTC
RTC time: Fri 2021-12-17 03:09:34
Time zone: Australia/Melbourne (AEDT, +1100)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no
```
**To Reproduce**  
1. Installation
```
HOMEDIR="/opt/akamai-uls"
VENV_DIR="$HOMEDIR/uls"
ULS_DIR="$VENV_DIR/app"
EXT_DIR="$ULS_DIR/ext"
ETP_CLI_VERSION="0.3.5"
LOG_DIR="/var/log/akamai"
yum install -y ca-certificates git curl gcc python3
python3 -m venv ${VENV_DIR}
source ${VENV_DIR}/bin/activate
git clone --single-branch https://github.com/akamai/uls.git ${ULS_DIR}
pip3 install -r ${ULS_DIR}/bin/requirements.txt
git clone --depth 1 -b "${ETP_CLI_VERSION}" --single-branch https://github.com/akamai/cli-etp.git ${EXT_DIR}/cli-etp
vi ${HOMEDIR}/.edgerc 
[default]
; Akamai {OPEN} API credentials (FOR EAA-HEALTH & all ETP logs)
host = akaa-xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx.luna.akamaiapis.net
client_token = akab-xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx
client_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
access_token = akab-xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx
; ETP Config
etp_config_id = your-ETP-config-ID
```
2. Runtime execution
```
/opt/akamai-uls/uls/bin/python3 /opt/akamai-uls/uls/bin/uls.py --input etp --feed THREAT --edgerc /opt/akamai-uls/uls/.auth/.edgerc --output file --filename /var/log/splunk/akamai/etp_THREAT/etp_THREAT.log --filehandler time --filetime midnight --filebackupcount 5 --inproxy REDACTED-IP:8080
/opt/akamai-uls/uls/bin/python3 /opt/akamai-uls/uls/bin/uls.py --input etp --feed AUP --edgerc /opt/akamai-uls/uls/.auth/.edgerc --output file --filename /var/log/splunk/akamai/etp_AUP/etp_AUP.log --filehandler time --filetime midnight --filebackupcount 5 --inproxy REDACTED-IP:8080
/opt/akamai-uls/uls/bin/python3 /opt/akamai-uls/uls/bin/uls.py --input etp --feed DNS --edgerc /opt/akamai-uls/uls/.auth/.edgerc --output file --filename /var/log/splunk/akamai/etp_DNS/etp_DNS.log --filehandler time --filetime midnight --filebackupcount 5 --inproxy REDACTED-IP:8080
```

3. List files (e.g. ls -lRh, ll -R) - refer to screenshots

**Expected behavior**  
Datestamp in backup filename should match actual file creation date

**Screenshots**  
2 screenshots attached 

**ULS Version output**  
please run the following and attach the output here.
```bash
bin/uls.py --version
Traceback (most recent call last):
File "bin/uls.py", line 30, in <module>
import modules.UlsTransformation as UlsTransformation
File "/opt/akamai-uls/uls/bin/modules/UlsTransformation.py", line 22, in <module>
import jmespath
ModuleNotFoundError: No module named 'jmespath'
```
Manual Checks
```
ULS Version             1.2.0
ETP Version             0.3.5
Python Version          3.6.8
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.3 (Ootpa)

jmespath is in
lib/python3.6/site-packagesjmespath
lib64/python3.6/site-packagesjmespath
```
**Additional context**  
![ss1](https://user-images.githubusercontent.com/97641303/149247201-a7465af4-1b01-4830-a7f4-85a3f2dba07c.jpg)
![ss2](https://user-images.githubusercontent.com/97641303/149247225-14cd5e0f-73e2-4e04-824e-e4096623e0ac.jpg)

**Comment by fami-t** [comment] 2022-01-13 10:53
Hi @MikeSchiessl ,

Thanks for your speedy reply. Appreciate that the upgrade of versions would be the first ask.  Will see what can be done about spinning up an env to test the upgrade. Maybe an internal question for my side why "yum install python3" ended up installing version 3.6.8 though it's not a path to a solution.

Let me know how the midnight rotation goes at your end. Thanks.

Regards,
Fami

**Comment by MikeSchiessl** [comment] 2022-01-13 13:38
Hey @fami-t , 

I've set up the same "pattern" as you did, the only difference is that I am running it from within a docker container (as I am not having anything pythonic installed on the base OS).

```
docker run -d -ti --rm \
    --mount type=bind,source="/opt/docker/akamai-uls/.edgerc",target="/path_to_my_storage/akamai-uls/.edgerc",readonly \
    --mount type=bind,source="/opt/docker/akamai-uls/mike-test/",target="/opt/akamai-uls/storage" \
    --name "mike-uls" \
    akamai/uls \
    --input etp --feed THREAT --output file --filename /path_to_my_storage/akamai-uls/storage/etp_THREAT.log --filehandler time --filetime midnight --filebackupcount 5
```

The box I am running on is setup UTC (same as the datetime within the docker container).
Here's my --version output (just to be transparent)

```
./uls.py -v
Akamai Unified Log Streamer Version information
ULS Version		1.3.0

EAA Version		0.4.5
ETP Version		0.3.6
MFA Version		0.0.6

OS Plattform		Linux-5.11.0-1022-aws-x86_64-with-glibc2.31
OS Version		5.11.0-1022-aws
Python Version		3.10.1
Docker Status		True
RootPath 		/opt/akamai-uls/uls
```

The first file has been created properly - waiting now for the midnight chime :D 
![image](https://user-images.githubusercontent.com/77062930/149340349-93a57287-81d0-415c-9090-1232a8ca3568.png)

Best 
Mike

**Comment by MikeSchiessl** [comment] 2022-01-14 08:51
Good news (is it ?), i can confirm the issue:
![image](https://user-images.githubusercontent.com/77062930/149486304-0a0476b7-b39d-46a9-be3a-4ad4ee348fc9.png)

rollover last night gave me a rotated filename: `etp_THREAT.log.2021-12-15`

I'll need to dig into this one, as I have absolutely no clue what is going on here.
Pretty weird - but that's a brilliant catch - thanks for this one.

Will need to carve out some debugging time on that topic - I'll report back on what I've got

**Comment by MikeSchiessl** [comment] 2022-01-14 12:21
Hi @fami-t, i think i've spotted something.
Having had a closer look to the s[ource code of the logging handler](https://github.com/python/cpython/blob/cb589d1b6bad4b75852c2e2a471a3800d5efdca7/Lib/logging/handlers.py), It seems the ULS default "interval" value within the config screwed up.

The problem: midnight is identically handled as "day" - so if midnight is specified with an interval > 1, it will rather rotate towards the days.

```
output_file_time_interval = 30 
```

I've now changed my setup, giving the interval of 1 manually.

Adding the following flag:
`--fileinterval 1`


So your commands should look like the following:
```
/opt/akamai-uls/uls/bin/python3 /opt/akamai-uls/uls/bin/uls.py --input etp --feed THREAT --edgerc /opt/akamai-uls/uls/.auth/.edgerc --output file --filename /var/log/splunk/akamai/etp_THREAT/etp_THREAT.log --filehandler time --filetime midnight --fileinterval 1 --filebackupcount 5 --inproxy REDACTED-IP:8080
/opt/akamai-uls/uls/bin/python3 /opt/akamai-uls/uls/bin/uls.py --input etp --feed AUP --edgerc /opt/akamai-uls/uls/.auth/.edgerc --output file --filename /var/log/splunk/akamai/etp_AUP/etp_AUP.log --filehandler time --filetime midnight --fileinterval 1 --filebackupcount 5 --inproxy REDACTED-IP:8080
/opt/akamai-uls/uls/bin/python3 /opt/akamai-uls/uls/bin/uls.py --input etp --feed DNS --edgerc /opt/akamai-uls/uls/.auth/.edgerc --output file --filename /var/log/splunk/akamai/etp_DNS/etp_DNS.log --filehandler time --filetime midnight --fileinterval 1 --filebackupcount 5 --inproxy REDACTED-IP:8080
```

I will fix the bug in the next release and will leave this ticket open until I got this sorted in the code


Best
Mike

**Comment by MikeSchiessl** [comment] 2022-01-14 13:55
Just for the record: 

I've raised a [bug on python.org](https://bugs.python.org/issue46377) and proposed a [pull request](https://github.com/python/cpython/pull/30599) to get this sorted as well.

**Comment by fami-t** [comment] 2022-01-16 05:28
Hi @MikeSchiessl , thank you for the quick work to track this down.

I'll get this change raised to add the `--fileinterval 1` flag and post an update after a file rotation.

I'll make a note to keep an eye on the first Sunday of April when daylight savings time `AEDT` ends (as sanity check).

Saw your conversation with Vinay on the TimedRotatingFileHandler issue. Hopefully the issue you raise will be a signpost for "unsuspecting" others until the time interval of 1 is enforced for `when=midnight`

Best regards,
Fami

**Comment by MikeSchiessl** [comment] 2022-01-16 18:24
Hey @fami-t ,

thanks for coming back to me.
I've just checked on my test boxes and it seems to work perfectly.
![image](https://user-images.githubusercontent.com/77062930/149672647-06e487a4-c92f-4b38-a24e-08a389ff4fca.png)


Anyway, I've already pushed a ULS fix to my internal dev branch which will reflect in the next version.
Not sure the python bug list will pick up the issue (I think you've seen the discussion), anyway it is documented now - and if someone searches for the timebased wrapper + midnight attribute, he should be able to at least find the bug and safe some time ;)

Let me know if this is working for you, so we can close this bug off.
I'll also have a look at the other one you've [raised](https://github.com/akamai/uls/issues/19), tomorrow but I feel this might not really be ULS related - but due to the very "edgy" timezone, worth to double check things on ULS side as well ;) 
Happy (rest of) sunday ! 

Mike

**Comment by fami-t** [comment] 2022-01-19 00:06
Hi @MikeSchiessl, 

Am planning to get this changed on Friday night and will report back on Saturday (Jan 22).

Many thanks.
Mit freundlichen Grüßen ;-)

**Comment by fami-t** [comment] 2022-01-21 13:36
Hi @MikeSchiessl ,

I had a bit of brain fade and forgot to run `systemctl daemon-reload` after adding the fileinterval parameter to the services file just before midnight rollover. Fixed now but can only verify after the next rotation. Will update you accordingly.

Regards,
Fami

**Comment by MikeSchiessl** [comment] 2022-01-21 13:41
Hi @fami-t,

no worries at all. I hope it works as well on your side as it works in the environment I've implemented.
Fingers crossed !


regards,
mike

**Comment by fami-t** [comment] 2022-01-24 03:25
Good morning @MikeSchiessl ,
Confirming that adding `--fileinterval 1` worked as expected:
```
./etp_AUP:
total 617344
-rw-r--r--. 1 akamai akamai  38302724 Jan 24 14:04 etp_AUP.log
-rw-r--r--. 1 akamai akamai 151662445 Jan 19 23:59 etp_AUP.log.2021-12-21
-rw-r--r--. 1 akamai akamai 100784245 Jan 20 23:59 etp_AUP.log.2021-12-22
-rw-r--r--. 1 akamai akamai 104415013 Jan 21 23:59 etp_AUP.log.2021-12-23
-rw-r--r--. 1 akamai akamai 123848560 Jan 22 23:59 etp_AUP.log.2022-01-22
-rw-r--r--. 1 akamai akamai 109219704 Jan 23 23:59 etp_AUP.log.2022-01-23

./etp_DNS:
total 62010920
-rw-r--r--. 1 akamai akamai  4715759985 Jan 24 14:03 etp_DNS.log
-rw-r--r--. 1 akamai akamai 14341670881 Jan 19 23:59 etp_DNS.log.2021-12-21
-rw-r--r--. 1 akamai akamai 14260375093 Jan 20 23:59 etp_DNS.log.2021-12-22
-rw-r--r--. 1 akamai akamai 14055021066 Jan 21 23:58 etp_DNS.log.2021-12-23
-rw-r--r--. 1 akamai akamai  8985253267 Jan 22 23:59 etp_DNS.log.2022-01-22
-rw-r--r--. 1 akamai akamai  6943134671 Jan 23 23:59 etp_DNS.log.2022-01-23

./etp_THREAT:
total 610580
-rw-r--r--. 1 akamai akamai  38358425 Jan 24 14:03 etp_THREAT.log
-rw-r--r--. 1 akamai akamai 151775695 Jan 19 23:59 etp_THREAT.log.2021-12-21
-rw-r--r--. 1 akamai akamai 101197103 Jan 20 23:59 etp_THREAT.log.2021-12-22
-rw-r--r--. 1 akamai akamai  99329499 Jan 21 23:59 etp_THREAT.log.2021-12-23
-rw-r--r--. 1 akamai akamai 124289567 Jan 22 23:59 etp_THREAT.log.2022-01-22
-rw-r--r--. 1 akamai akamai 110003786 Jan 23 23:59 etp_THREAT.log.2022-01-23
```

I think you can close this issue. Many thanks for your workaround and final fix.

Regards,
Fami

**Comment by MikeSchiessl** [comment] 2022-01-24 09:03
@fami-t  

thanks for checking !!! 
I am glad it worked out as expected  ;) 

You will find a fix for this issue in the next ULS release.

**Closed by MikeSchiessl** 2022-01-24 09:03 UTC
Labels: bug
