### ISSUE TITLE
[BUG] Some ETP DNS log records are showing event timestamps in the future

### ISSUE THREAD

**Issue by fami-t** [akamai/uls#19] opened 2022-01-13 12:13 UTC
**Describe the bug**
ULS client is configured for ETP THREAT, AUP & DNS feeds output to file, rotated at midnight, with 5 backup files.
**Some** ETP DNS log records are showing event timestamps in the future. 
For example:

- Sample of ETP DNS feed file records ingested into Splunk on 11-Jan-22 at around 17:07 – 18:51 UTC+11:00 (indextime in screenshot), have a source log record query time set in Zulu/UTC at around 2022-01-11T23:44:54Z to 2022-01-11T23:55:07Z (query.time in screenshot) which is 12-Jan-22 around 10:44am to 10:55am i.e. in the future.
- This is not a once-off occurrence but it does not occur with all event records received.

It's unclear if this is potentially an issue with the ULS client (hence this Issue ticket), or Akamai ETP backend (will raise Akamai support case too).

**To Reproduce**  
Refer to environment setup described in #18 

**Expected behavior**  

**Screenshots**  

**ULS Version output**  
As described in #18
```
bin/uls.py --version
Traceback (most recent call last):
File "bin/uls.py", line 30, in <module>
import modules.UlsTransformation as UlsTransformation
File "/opt/akamai-uls/uls/bin/modules/UlsTransformation.py", line 22, in <module>
import jmespath
ModuleNotFoundError: No module named 'jmespath'
```
Manual Checks
```
ULS Version             1.2.0
ETP Version             0.3.5
Python Version          3.6.8
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.3 (Ootpa)

jmespath is in
lib/python3.6/site-packagesjmespath
lib64/python3.6/site-packagesjmespath
```
**Additional context**  
![ss2](https://user-images.githubusercontent.com/97641303/149327476-2d1c12b7-07ab-41ff-ae2b-8be0818c4154.jpg)

**Comment by MikeSchiessl** [comment] 2022-01-17 08:25
Hi @fami-t, 
sorry for the delay in picking that one up.

This is a really tricky one, as you correctly stated, the root cause could also reside within the data delivered by API.
Anyway, let's play a little "Dr. House" game and pretend that API is not the root cause - so it has to be ULS or the chain behind (again this is just hypothetically, to get my brain working Monday morning ;) )

**First of all some "statements" regarding ULS**
- ULS has no chance to modify/touch the passed event data (except for transformations which I'd like to exclude for your use case - based on the command lines given in issue #18 )
- By default, everything within ULS is (by default) set to use the hosts/docker timezone
- ULS is writing the data sequentially into a log file (FIFO) - if something is arriving out of order in ULS, it gets written out of order into the file as well


**Potential root causes**
- [ ] Bug in --starttime --endtime feature (but you're not using this according to the issue #18 ) 
- [ ] Bug in the CLI ( - maybe calculating an abstruse **start time** in edgy TZ's ...)
- [ ] ULS file writer feels to amend some date (ok this is really far off)
- [ ] Splunk misinterpreting the timestamp 
- [ ]  ... to be amended


@fami-t: are you able to identify the corresponding events within the log file itself (this would help to exclude or blame Splunk and the transport layers in between)
Please let me know if any of my assumptions above do not make any sense - I'll wrap my head around the potential RC's.


Best
Mike

**Comment by fami-t** [comment] 2022-01-19 00:08
Hi @MikeSchiessl , apologies for the delay (caught up with a few other things) I will revert shortly today (missed taking a copy of the source log file I reported the issue on also ;-(

Regards
Fami

**Comment by fami-t** [comment] 2022-01-19 13:09
Hi @MikeSchiessl ,

Apologies for the late reply.  To answer your questions:
Agreed, regarding your assumptions:
-	We did not specify any transformation parameter.  As I understand it, the data written to file should be as captured by the CLI ETP code
-	The issue is not about the time ordered sequencing of data received but the query time field in the log record being after the time at which the data was written to disk by the ULS/CLI ETP client

Regarding potential causes
-	We have not specified `–starttime` or `–endtime`
-	Regarding Splunk (mis)interpretation of timestamps, one simple counter example is the **ETP DNS log file** written to disk with filename **etp_DNS.log.2021-11-15** having **OS file timestamp = Dec 14 23:59 AEDT (UTC+11:00)** that contains 296 records with `"query": {"time": "2021-12-15Thh:mm:ssZ"` for example `"2021-12-15T04:49:56Z"`.  This is one of files I listed in #18 
-	The entire log file is 12GB, 230MB bzip2.  The extracted 296 records are 367 KB though. I'll drop you a mail about how to get you the data.

Regards,
Fami

**Comment by MikeSchiessl** [comment] 2022-01-19 14:56
**Looking closer at the underlying CLI (ETP)**

So [from the code](https://github.com/akamai/cli-etp/blob/b2177270924113ab3de7c79dbfe69615d933757a/bin/akamai-etp#L178), the CLI uses `time.time()` to retrieve the current EPOCH timestamp in UTC

From the [regarding API docs](https://developer.akamai.com/api/enterprise_security/enterprise_threat_protector_reporting/v3.html#87859404), the request post data is expecting the EPOCH timestamp as well

_Summary:_
The calculated CLI timestamp fits the timestamp expected in the API POST payload
Based on that, I would exclude a bug in the CLI <-> API stuff.

**Comment by MikeSchiessl** [comment] 2022-02-01 07:58
Just an update to this topic:
I aligned with the Akatec team on this topic on the API Case - this seems to be the most promising approach right now, as I am really out of ideas on the ULS side.

As discussed, well leave this ticket open until the issue is resolved one or the other way ;)

**Comment by fami-t** [comment] 2022-04-02 14:28
Hi @MikeSchiessl , just a keepalive message that I received note from your colleague (AD) that he's awaiting an update from the ETP engineering team responsible for the ETP event log API backend, as the issue is upstream of ULS.

**Comment by MikeSchiessl** [comment] 2022-04-04 08:04
Hi Fami,

I would not have allowed "stale bot" to close this one ;) 
Actually, I am in close exchange with AD and also involved in the internal tickets.
Once the issue is mitigated, we will close this ticket, but not earlier.

Best
Mike

**Comment by MikeSchiessl** [comment] 2022-04-28 13:01
Hi @fami-t ,
just saw your response to the propagated fix on this issue (API-wise).
Should we leave this open or are you good to close this issue off ?

Best regards
Mike

**Comment by fami-t** [comment] 2022-04-29 10:05
Hi @MikeSchiessl ,

Good to close this issue as it has not recurred since the upstream fix (outside of ULS) was deployed on 21-April-2022.

All the best.
Fami

**Comment by MikeSchiessl** [comment] 2022-04-29 10:37
Hey @fami-t ,

thanks for confirming.
Feel free to open another issue or re-open this one if you have any trouble with ULS .
Have a great weekend !

Best 
Mike

**Closed by MikeSchiessl** 2022-04-29 10:37 UTC
Labels: 3rd party support
